name: Bypass Branch Protection

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - master

jobs:
  bypass-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install requests

    - name: Run bypass script
      env:
        GITHUB_OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
      run: |
        source venv/bin/activate
        python scripts/auto_bypass_branch_protection.py
